#!/usr/bin/env node
/**
 * One-time content extraction script.
 * Reads curriculum.json + markdown files from the AILearning repo
 * and outputs src/content/curriculum.ts with all content inline.
 *
 * Usage: node scripts/extract-content.mjs /path/to/AILearning
 */
import fs from "fs";
import path from "path";

const WORDS_PER_MINUTE = 230;
const repoPath = process.argv[2] || "/tmp/AILearning-clone";
const curriculumPath = path.join(repoPath, "backend/src/data/curriculum.json");
const contentDir = path.join(repoPath, "content");
const outPath = path.join(
  import.meta.dirname,
  "../src/content/curriculum.ts"
);

const curriculum = JSON.parse(fs.readFileSync(curriculumPath, "utf-8"));

function wordCount(text) {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function readingTime(words) {
  return Math.max(1, Math.ceil(words / WORDS_PER_MINUTE));
}

// Build eras
const eras = curriculum.eras.map((e) => ({
  id: e.id,
  name: e.name,
  description: e.description,
  color: e.color,
  order: e.order,
}));

// Build topics with inline lesson content
const topics = curriculum.topics.map((t) => {
  const lessons = t.lessons
    .filter((l) => l.lessonType === "content")
    .map((l) => {
      const mdPath = path.join(contentDir, l.contentPath);
      let content = "";
      try {
        content = fs.readFileSync(mdPath, "utf-8");
      } catch (err) {
        console.warn(`Missing: ${mdPath}`);
      }
      const words = wordCount(content);
      return {
        slug: l.slug,
        title: l.title,
        lessonOrder: l.lessonOrder,
        content,
        wordCount: words,
        readingTimeMinutes: readingTime(words),
      };
    })
    .sort((a, b) => a.lessonOrder - b.lessonOrder);

  return {
    slug: t.slug,
    title: t.title,
    description: t.description,
    eraId: t.era,
    linearOrder: t.linearOrder,
    icon: t.icon,
    estimatedMinutes: t.estimatedMinutes,
    lessons,
  };
});

// Stats
const totalLessons = topics.reduce((a, t) => a + t.lessons.length, 0);
const totalWords = topics.reduce(
  (a, t) => a + t.lessons.reduce((b, l) => b + l.wordCount, 0),
  0
);
console.log(`Extracted ${topics.length} topics, ${totalLessons} lessons`);
console.log(`Total words: ${totalWords.toLocaleString()}`);
console.log(`Est. reading time: ${readingTime(totalWords)} minutes`);

// Generate TypeScript
const tsContent = `// Auto-generated by scripts/extract-content.mjs — do not edit
import type { Era, Topic } from '../types';

export const eras: Era[] = ${JSON.stringify(eras, null, 2)};

export const topics: Topic[] = ${JSON.stringify(topics, null, 2)};

export const totalLessons = ${totalLessons};
export const totalWords = ${totalWords};
export const estimatedTotalMinutes = ${readingTime(totalWords)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, tsContent, "utf-8");
console.log(`Written to ${outPath}`);
